### ISSUE TITLE
Jump also selects text

### ISSUE THREAD

**Issue by introom** [AlexPl292/IdeaVim-EasyMotion#86]
After jumping, for example, with easymotion-s, the text is also selected.
Before jump. Cursor is on "sed".
<img width="858" alt="image" src="https://user-images.githubusercontent.com/669045/198842415-e59c7550-46a2-441b-8a9a-b61fe5cdd45c.png">
After use easymotion-s2 with chars "LA".  The text is also highlighted.
<img width="733" alt="image" src="https://user-images.githubusercontent.com/669045/198842421-7d6c5ed9-2829-4c4e-b811-9047965c8c17.png">

My mapping is: 
nmap <A-o> <Plug>(easymotion-s2)

I also spotted a similar issue on stackoverflow, 
https://stackoverflow.com/questions/60491336/why-ideavim-easymotion-plugin-for-pycharm-selects-the-text-between-cursors-inste

**Comment by AlexPl292** [comment]
Do you use capital letters for a jump? You should use lowercase letters.

**Comment by introom** [comment]
Thanks. Using lowercase works. I used capital because the overlay char shows in capital. That could be feature that I misunderstand.

**Comment by AlexPl292** [comment]
@breandan this is not the first time I have seen users using the uppercase letters. Have you seen the same bugs? Maybe we can use lowercase letters on labels?

**Comment by breandan** [comment]
Yes, we have a [feature request](https://github.com/acejump/AceJump/issues/352) along these lines which should be fairly simple to implement. The only tricky part is that lower case letters have different bounding boxes, so changes to [`TagMarker`](https://github.com/acejump/AceJump/blob/f17f4ef8c41cbc3efb031f88dca13b711cb34c51/src/main/kotlin/org/acejump/view/TagMarker.kt) are needed so that it does not look ugly.
